apiVersion: batch/v1
kind: Job
metadata:
  name: sqlite-restore-point
  namespace: pra
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: restore
          image: alpine
          command: ["/bin/sh","-c"]
          args:
            - |
              BACKUP_FILE=${RESTORE_POINT:-$(ls -t /backup/*.db | head -1)}
              echo "Restauration depuis : $BACKUP_FILE"
              if [ ! -f "$BACKUP_FILE" ]; then
                echo "Erreur : fichier $BACKUP_FILE introuvable"
                ls /backup/
                exit 1
              fi
              cp $BACKUP_FILE /data/app.db
              echo "Restauration terminée avec succès"
          env:
            - name: RESTORE_POINT
              value: "/backup/app-1782985441.db"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: backup
              mountPath: /backup
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pra-data
        - name: backup
          persistentVolumeClaim:
            claimName: pra-backup
